name: github
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  infinite_scroll_pagination: ^5.1.0
  injectable: ^2.5.0
  pretty_dio_logger: ^1.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  mockito: ^5.4.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

